
/*
 * 
 */

package se.vgregion.metaservice.keywordservice.intsvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import keywordservices.wsdl.metaservice_vgr_se.v2.KeywordService;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Nov 18 13:24:52 CET 2009
 * Generated source version: 2.1.1
 * 
 */
 
/*
 * 
 */

@WebServiceClient(name = "KeywordServiceIntServiceImplService", 
                  wsdlLocation = "http://metadataservice.vgregion.se/keywordservice/KeywordService?wsdl",
                  targetNamespace = "http://intsvc.keywordservice.metaservice.vgregion.se/") 
public class KeywordServiceIntServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://intsvc.keywordservice.metaservice.vgregion.se/", "KeywordServiceIntServiceImplService");
    public final static QName KeywordServiceIntServiceImplPort = new QName("http://intsvc.keywordservice.metaservice.vgregion.se/", "KeywordServiceIntServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://metadataservice.vgregion.se/keywordservice/KeywordService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://metadataservice.vgregion.se/keywordservice/KeywordService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public KeywordServiceIntServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KeywordServiceIntServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeywordServiceIntServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns KeywordService
     */
    @WebEndpoint(name = "KeywordServiceIntServiceImplPort")
    public KeywordService getKeywordServiceIntServiceImplPort() {
        return super.getPort(KeywordServiceIntServiceImplPort, KeywordService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeywordService
     */
    @WebEndpoint(name = "KeywordServiceIntServiceImplPort")
    public KeywordService getKeywordServiceIntServiceImplPort(WebServiceFeature... features) {
        return super.getPort(KeywordServiceIntServiceImplPort, KeywordService.class, features);
    }

}
