
package keywordservices.wsdl.metaservice_vgr_se.v2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import se.vgregion.metaservice.keywordservice.intsvc.KeywordServiceIntServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Nov 18 13:24:52 CET 2009
 * Generated source version: 2.1.1
 * 
 */

public final class KeywordService_KeywordServiceIntServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://intsvc.keywordservice.metaservice.vgregion.se/", "KeywordServiceIntServiceImplService");

    private KeywordService_KeywordServiceIntServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = KeywordServiceIntServiceImplService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        KeywordServiceIntServiceImplService ss = new KeywordServiceIntServiceImplService(wsdlURL, SERVICE_NAME);
        KeywordService port = ss.getKeywordServiceIntServiceImplPort();  
        
        {
        System.out.println("Invoking bookmarkKeywords...");
        keywordservices.wsdl.metaservice_vgr_se.v2.BookmarkKeywordsRequest _bookmarkKeywords_parameters = null;
        se.vgr.metaservice.schema.response.v1.ResponseObjectType _bookmarkKeywords__return = port.bookmarkKeywords(_bookmarkKeywords_parameters);
        System.out.println("bookmarkKeywords.result=" + _bookmarkKeywords__return);


        }
        {
        System.out.println("Invoking getKeywords...");
        keywordservices.wsdl.metaservice_vgr_se.v2.GetKeywordsRequest _getKeywords_parameters = null;
        se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType _getKeywords__return = port.getKeywords(_getKeywords_parameters);
        System.out.println("getKeywords.result=" + _getKeywords__return);


        }
        {
        System.out.println("Invoking getNodeByInternalId...");
        keywordservices.wsdl.metaservice_vgr_se.v2.GetNodeByInternalIdRequest _getNodeByInternalId_parameters = null;
        se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType _getNodeByInternalId__return = port.getNodeByInternalId(_getNodeByInternalId_parameters);
        System.out.println("getNodeByInternalId.result=" + _getNodeByInternalId__return);


        }
        {
        System.out.println("Invoking tagKeywords...");
        keywordservices.wsdl.metaservice_vgr_se.v2.TagKeywordsRequest _tagKeywords_parameters = null;
        se.vgr.metaservice.schema.response.v1.ResponseObjectType _tagKeywords__return = port.tagKeywords(_tagKeywords_parameters);
        System.out.println("tagKeywords.result=" + _tagKeywords__return);


        }

        System.exit(0);
    }

}
