
/*
 * 
 */

package keywordservices.wsdl.metaservice_vgr_se.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Nov 18 13:24:52 CET 2009
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2", name = "KeywordService")
@XmlSeeAlso({se.vgr.metaservice.schema.document.v1.ObjectFactory.class,se.vgr.metaservice.schema.response.v1.ObjectFactory.class,ObjectFactory.class,se.vgr.metaservice.schema.node.v2.ObjectFactory.class,se.vgr.metaservice.schema.request.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface KeywordService {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "BookmarkKeywordsResponse", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    @WebMethod(operationName = "BookmarkKeywords")
    public se.vgr.metaservice.schema.response.v1.ResponseObjectType bookmarkKeywords(
        @WebParam(partName = "parameters", name = "BookmarkKeywordsRequest", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2")
        BookmarkKeywordsRequest parameters
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetKeywordsResponse", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    @WebMethod(operationName = "GetKeywords")
    public se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType getKeywords(
        @WebParam(partName = "parameters", name = "GetKeywordsRequest", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2")
        GetKeywordsRequest parameters
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetNodeByInternalIdResponse", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    @WebMethod(operationName = "GetNodeByInternalId")
    public se.vgr.metaservice.schema.response.v1.NodeListResponseObjectType getNodeByInternalId(
        @WebParam(partName = "parameters", name = "GetNodeByInternalIdRequest", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2")
        GetNodeByInternalIdRequest parameters
    );

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "TagKeywordsResponse", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2", partName = "parameters")
    @WebMethod(operationName = "TagKeywords")
    public se.vgr.metaservice.schema.response.v1.ResponseObjectType tagKeywords(
        @WebParam(partName = "parameters", name = "TagKeywordsRequest", targetNamespace = "urn:KeywordServices:wsdl:metaservice.vgr.se:v2")
        TagKeywordsRequest parameters
    );
}
